services:
  fitcoach-ia:
    container_name: fitcoach-ia
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
