services:
  fitcoach-ia:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fitcoach-ia
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true
