name: Python setup custom
description: Install python version indicated and install dependencies with uv

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # instala el binario de uv para instalar las dependencias
    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: ".github/requirements-ci.txt"
        version: "latest"


    - name: Requirements security analysis
      shell: bash
      run: |
         echo "Analizando las dependencias a instalar en un step posterior para verificar si tienen vulnerabilidades:"
         echo "--> -s osv: Uso del servicio de vulnerabilidades OSV"
         echo "--> -f json: Formato del fichero de salida"
         echo "--> -o audit.json: Fichero de salida con el resultado."

         if command -v jq >/dev/null 2>&1; then
          echo "Lanzamos análisis y obtenemos la salida en un fichero donde verificaremos si tiene dependencias criticas"
          uvx pip-audit -s osv -r .github/requirements-ci.txt -f json -o audit.json || true
          echo "Validando la criticidad de las vulnerabilidades (critical == 0 ó high == 0 -> OK)"
          CRITICAL_COUNT=$(jq '[.dependencies[].vulns[] | select(.cvss_v3_severity == "CRITICAL" or .cvss_v3_severity == "HIGH")] | length' audit.json)
          if [ "$CRITICAL_COUNT" -ne "0" ]; then
            echo "Se han encontrado $CRITICAL_COUNT vulnerabilidades críticas o altas."
            jq '.dependencies[].vulns[] | select(.cvss_v3_severity == "CRITICAL" or .cvss_v3_severity == "HIGH")' audit.json
            exit 1
          else
            echo "No se han encontrado vulnerabilidades de riesgo alto."
          fi
         else
           echo "jq no disponible. Ejecutamos el análisis sin verificar criticidades"
           uvx pip-audit -s osv -r .github/requirements-ci.txt

    # Instala las dependencias necesarias del proyecto.
    # requirements-ci.txt incluye dependencias de build.yaml además de las dependencias del proyecto
    - name: Install dependencies
      shell: bash
      run: uvx pip install --system -q -r .github/requirements-ci.txt
