"""Validated exercise proposals and their moderation lifecycle."""

from datetime import datetime
from enum import StrEnum
from typing import Annotated, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)

from fitcoach.domain.exercise_catalogue import (
    MUSCLE_TARGETS,
    canonical_group,
    known_equipment,
    normalize_equipment,
)

ShortText = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=120)]
InstructionText = Annotated[
    str, StringConstraints(strip_whitespace=True, min_length=10, max_length=2000)
]
ExerciseSubmissionAction = Literal["confirm", "cancel"]
_KNOWN_TARGETS = frozenset(target for targets in MUSCLE_TARGETS.values() for target in targets)


class ExerciseSubmissionStatus(StrEnum):
    DRAFT = "draft"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    CANCELLED = "cancelled"


class ExerciseQualityAssessment(BaseModel):
    """Model-generated review aid; moderators remain the final authority."""

    model_config = ConfigDict(extra="forbid")

    validity: Literal["valid", "uncertain", "invalid"] = "uncertain"
    confidence: float = Field(default=0.0, ge=0, le=1)
    rationale: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=1, max_length=500)
    ] = "Pending model assessment."
    safety_notes: list[
        Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=200)]
    ] = Field(default_factory=list, max_length=5)


class ExerciseProposal(BaseModel):
    """Canonical fields accepted by the existing exercise catalogue."""

    model_config = ConfigDict(extra="forbid")

    name: ShortText
    category: ShortText
    body_part: ShortText
    equipment: ShortText
    target: ShortText
    secondary_muscles: list[ShortText] = Field(max_length=8)
    instructions_en: InstructionText
    quality: ExerciseQualityAssessment = Field(default_factory=ExerciseQualityAssessment)

    @field_validator("equipment")
    @classmethod
    def _known_equipment(cls, value: str) -> str:
        normalized = normalize_equipment(value)
        if normalized not in known_equipment():
            raise ValueError("Unknown equipment")
        return normalized

    @field_validator("target")
    @classmethod
    def _known_target(cls, value: str) -> str:
        normalized = value.lower()
        if normalized not in _KNOWN_TARGETS:
            raise ValueError("Unknown target")
        return normalized

    @field_validator("secondary_muscles")
    @classmethod
    def _unique_secondary_muscles(cls, values: list[str]) -> list[str]:
        normalized = [value.lower() for value in values]
        if len(set(normalized)) != len(normalized):
            raise ValueError("Secondary muscles must be unique")
        return normalized

    @property
    def muscle_group(self) -> str:
        group = canonical_group(self.target)
        if group is None:
            raise ValueError("Target has no canonical muscle group")
        return group


class ExerciseCuratorTurn(BaseModel):
    """Structured result generated by the curator model."""

    model_config = ConfigDict(extra="forbid")

    status: Literal["proposal", "clarification", "rejected"]
    reply: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=800)]
    proposal: ExerciseProposal | None

    @model_validator(mode="after")
    def _proposal_matches_status(self) -> "ExerciseCuratorTurn":
        if (self.status == "proposal") != (self.proposal is not None):
            raise ValueError("Only proposal turns may contain an exercise proposal")
        return self


def build_exercise_metadata_text(proposal: ExerciseProposal) -> str:
    """Build the same semantic fields used by the existing catalogue loader."""
    secondary = ", ".join(proposal.secondary_muscles)
    return " | ".join((
        f"name: {proposal.name}",
        f"category: {proposal.category}",
        f"body_part: {proposal.body_part}",
        f"equipment: {proposal.equipment}",
        f"muscle_group: {proposal.muscle_group}",
        f"target: {proposal.target}",
        f"secondary_muscles: {secondary}",
    ))


class ExerciseSubmission(BaseModel):
    """Persisted proposal, including provenance and moderation metadata."""

    model_config = ConfigDict(extra="forbid")

    id: int
    chat_id: int
    message_thread_id: int | None
    raw_description: str
    proposal: ExerciseProposal | None
    status: ExerciseSubmissionStatus
    model: str
    duplicate_exercise_id: int | None = None
    moderation_notes: str | None = None
    reviewed_by: int | None = None
    published_exercise_id: int | None = None
    created_at: datetime
    updated_at: datetime
    reviewed_at: datetime | None = None

    @model_validator(mode="after")
    def _completed_states_require_proposal(self) -> "ExerciseSubmission":
        if (
            self.status in {ExerciseSubmissionStatus.PENDING, ExerciseSubmissionStatus.APPROVED}
            and self.proposal is None
        ):
            raise ValueError("Pending and approved submissions require an exercise proposal")
        return self
