from datetime import datetime
from typing import Protocol

from fitcoach.domain.interviewer_profile import InterviewerProfile
from fitcoach.domain.training_lifecycle import Mesocycle, TrainingWorkflow


class TrainingConflictError(RuntimeError):
    """The proposal is stale or another request owns its generation."""


class TrainingRepository(Protocol):
    async def get_cycle(self, chat_id: int) -> Mesocycle | None: ...
    async def get_workflow(self, chat_id: int) -> TrainingWorkflow | None: ...
    async def start(self, chat_id: int, kind: str) -> TrainingWorkflow: ...
    async def save(self, chat_id: int, workflow: TrainingWorkflow) -> TrainingWorkflow: ...
    async def claim_generation(self, chat_id: int, workflow_id: int) -> TrainingWorkflow: ...
    async def accept(self, chat_id: int, workflow_id: int, start: datetime) -> int: ...
    async def cancel(self, chat_id: int) -> None: ...
    async def close_cycle(self, chat_id: int, now: datetime) -> None: ...
    async def set_start(self, chat_id: int, start: datetime) -> None: ...
    async def set_reminders(self, chat_id: int, enabled: bool) -> None: ...
    async def postpone(self, chat_id: int, until: datetime) -> None: ...
    async def effective_profile(self, chat_id: int) -> InterviewerProfile | None: ...
