from dataclasses import dataclass
from datetime import datetime
from typing import Literal, Protocol

from fitcoach.domain.interviewer_profile import InterviewerProfile
from fitcoach.domain.training_lifecycle import Mesocycle, TrainingWorkflow


class TrainingConflictError(RuntimeError):
    """The proposal is stale or another request owns its generation."""


@dataclass(frozen=True)
class ReminderDelivery:
    id: int
    chat_id: int
    thread_id: int | None
    attempts: int


class TrainingRepository(Protocol):
    async def get_cycle(self, chat_id: int) -> Mesocycle | None: ...
    async def get_workflow(self, chat_id: int) -> TrainingWorkflow | None: ...
    async def start(
        self, chat_id: int, kind: Literal["renewal", "exercise_swap"]
    ) -> TrainingWorkflow: ...
    async def save(self, chat_id: int, workflow: TrainingWorkflow) -> TrainingWorkflow: ...
    async def claim_generation(self, chat_id: int, workflow_id: int) -> TrainingWorkflow: ...
    async def accept(
        self, chat_id: int, workflow_id: int, start: datetime, expected_revision: int | None = None
    ) -> int: ...
    async def cancel(self, chat_id: int) -> None: ...
    async def close_cycle(
        self, chat_id: int, now: datetime, expected_plan_id: int | None = None
    ) -> None: ...
    async def set_start(self, chat_id: int, start: datetime) -> None: ...
    async def set_reminders(self, chat_id: int, enabled: bool) -> None: ...
    async def postpone(
        self, chat_id: int, until: datetime, expected_plan_id: int | None = None
    ) -> None: ...
    async def effective_profile(self, chat_id: int) -> InterviewerProfile | None: ...
    async def remember_thread(self, chat_id: int, thread_id: int | None) -> None: ...
    async def reserve_interaction_reminder(
        self, chat_id: int, thread_id: int | None, now: datetime
    ) -> ReminderDelivery | None: ...
    async def finish_reminder(
        self, delivery: ReminderDelivery, retry_at: datetime | None = None, failed: bool = False
    ) -> None: ...
