name: SSH connection
on:
    push:
       branches: [feature/project-structure] 

permissions: 
    contents: read

jobs:
    server-connection:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout project"
              id: step-checkout
              uses: actions/checkout@v6
              with:
                ref: feature/project-structure
                sparse-checkout: |
                    config 
                sparse-checkout-cone-mode: false

            - name: "Print directory"
              run: |
                echo $(ls -a)
            
            # - name: set key permissions
            #   run: chmod 600 ./id_ed25519

            # - name: "SSH access"
            #   run: | 
            #     ssh -i ./id_ed25519 \
            #         -o StrictHostKeyChecking=no \
            #         raul@81.46.246.130 \
            #         "echo $(nano .profile | sed -n '1, 7p')"




              
            
