name: workflow_sample
on:
    push:
       branches: [feature/project-structure] 

permissions: 
    contents: read

jobs:
    server-connection:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout project"
              id: step-checkout
              uses: actions/checkout@v6
              with:
                sparse-checkout: |
                    src/fitcoach/infrastucture/config/id_ed25519 
                sparse-checkout-cone-mode: false
            
            - name: set key permissions
              run: chmod 600 src/fitcoach/infrastucture/config/id_ed25519

            - name: "SSH access"
              run: | 
                ssh -i src/fitcoach/infrastucture/config/id_ed25519 \
                    -o StrictHostKeyChecking=no \
                    raul@81.46.246.130 \
                    "echo $(nano .profile | sed -n '1, 7p')"




              
            
